#####
# Odoo Dev Dockerfile 
#
FROM odoo-base
LABEL Maintainer="Cyril MORISSE <cmorisse@boxes3.net>"

ENV ODOO_VERSION 11.0

WORKDIR "/opt/odoo"

# We don't need to create directories as --volume will do it
#    && mkdir -p /opt/odoo/odoo_src && chown -R odoo /opt/odoo/odoo_src \
#    && mkdir -p /opt/odoo/project_addons && chown -R odoo /opt/odoo/project_addons \
#    && mkdir -p /opt/odoo/extra_addons && chown -R odoo /opt/odoo/extra_addons \
#    && mkdir -p /opt/odoo/etc && chown -R odoo /opt/odoo/etc

# Install IKP3db from sources to hack it
# /var/lib/odoo is mounted via run -v ...
COPY ikp3db ikp3db/
RUN  pip install -e /opt/odoo/ikp3db


# Install IKP3db from pypi or pypi test
#RUN pip install ikp3db
#RUN pip3 install --index-url=https://testpypi.python.org/simple/ ikp3db


# Expose Odoo services
EXPOSE 8069 8072 15499

# Set the default config file
ENV ODOO_RC /opt/odoo/etc/odoo.conf

ENTRYPOINT ["bin/odoo-docker-entrypoint.sh"]